s<-c(1,2,3,4,5,6,7)
a=readline("Enter the element that you want to find:")
print("The element is present in:")
print(match(a,s))
c=readline("Enter the eleent you want to check whether its in the vector or not:")
print(c%in%s)
mean(s)
median(s)
var(s)
sd(s)
scale(s)
summary(s)
rank(s)
quantile(s)
seq(1,10)
mean(1,10)
sum(1,10)
max(3,10)
pow[3,2]
